spring:
  application:
    name: axon-showcase-projection-service
  main:
    banner-mode: off
  data:
    elasticsearch:
      repositories:
        enabled: false
  jackson:
    default-property-inclusion: non_null
  web:
    locale: en
  webflux:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true

axon:
  serializer:
    messages: jackson
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    default-topic: ${KAFKA_TOPIC_EVENTS:axon-showcase-events}
    client-id: ${spring.application.name}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    publisher:
      enabled: false
    consumer:
      event-processor-mode: subscribing
      properties:
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
    fetcher:
      poll-timeout: ${KAFKA_FETCHER_POLL_TIMEOUT:5000}
      consumer-count: ${KAFKA_FETCHER_CONSUMER_COUNT:1}
  metrics:
    micrometer:
      dimensional: true
  tracing:
    repository:
      aggregate-id-attribute-name: axon.aggregateId

opensearch:
  uris: ${OS_URIS:http://localhost:9200}
  username: ${OS_USER:elastic}
  password: ${OS_PASSWORD:}
  connection-timeout: ${OS_CONNECTION_TIMEOUT:PT10S}
  socket-timeout: ${OS_SOCKET_TIMEOUT:PT30S}
  socket-keep-alive: ${OS_SOCKET_KEEP_ALIVE:true}
  max-connections: ${OS_MAX_CONNECTIONS:100}
  max-connections-per-route: ${OS_MAX_CONNECTIONS_PER_ROUTE:100}
  evict-idle-connections: ${OS_EVICT_IDLE_CONNECTIONS:PT5S}

resilience4j:
  enabled: ${RESILIENCE_ENABLED:true}
  circuitbreaker:
    enabled: ${CIRCUITBREAKER_ENABLED:true}
    configs:
      default:
        sliding-window-type: ${CIRCUITBREAKER_DEFAULT_SLIDING_WINDOW_TYPE:COUNT_BASED}
        sliding-window-size: ${CIRCUITBREAKER_DEFAULT_SLIDING_WINDOW_SIZE:100}
        minimum-number-of-calls: ${CIRCUITBREAKER_DEFAULT_MIN_REQUIRED_CALLS:50}
        failure-rate-threshold: ${CIRCUITBREAKER_DEFAULT_FAILURE_RATE_THRESHOLD:50}
        slow-call-rate-threshold: ${CIRCUITBREAKER_DEFAULT_SLOW_CALL_RATE_THRESHOLD:90}
        slow-call-duration-threshold: ${CIRCUITBREAKER_DEFAULT_SLOW_CALL_DURATION_THRESHOLD:PT5S}
        wait-duration-in-open-state: ${CIRCUITBREAKER_DEFAULT_WAIT_DURATION_IN_OPEN_STATE:PT10S}
        enable-exponential-backoff: true
        exponential-backoff-multiplier: ${CIRCUITBREAKER_DEFAULT_BACKOFF_MULTIPLIER_IN_OPEN_STATE:1.5}
        exponential-max-wait-duration-in-open-state: ${CIRCUITBREAKER_DEFAULT_MAX_WAIT_DURATION_IN_OPEN_STATE:}
        permitted-number-of-calls-in-half-open-state: ${CIRCUITBREAKER_DEFAULT_PERMITTED_CALLS_IN_HALF_OPEN_STATE:10}
        max-wait-duration-in-half-open-state: ${CIRCUITBREAKER_DEFAULT_MAX_WAIT_DURATION_IN_HALF_OPEN_STATE:PT0S}
        register-health-indicator: true
    instances:
      opensearch:
        base-config: default
        sliding-window-type: ${CIRCUITBREAKER_OPENSEARCH_SLIDING_WINDOW_TYPE:}
        sliding-window-size: ${CIRCUITBREAKER_OPENSEARCH_SLIDING_WINDOW_SIZE:}
        minimum-number-of-calls: ${CIRCUITBREAKER_OPENSEARCH_MIN_REQUIRED_CALLS:}
        failure-rate-threshold: ${CIRCUITBREAKER_OPENSEARCH_FAILURE_RATE_THRESHOLD:}
        slow-call-rate-threshold: ${CIRCUITBREAKER_OPENSEARCH_SLOW_CALL_RATE_THRESHOLD:}
        slow-call-duration-threshold: ${CIRCUITBREAKER_OPENSEARCH_SLOW_CALL_DURATION_THRESHOLD:}
        wait-duration-in-open-state: ${CIRCUITBREAKER_OPENSEARCH_WAIT_DURATION_IN_OPEN_STATE:}
        exponential-backoff-multiplier: ${CIRCUITBREAKER_OPENSEARCH_BACKOFF_MULTIPLIER_IN_OPEN_STATE:}
        exponential-max-wait-duration-in-open-state: ${CIRCUITBREAKER_OPENSEARCH_MAX_WAIT_DURATION_IN_OPEN_STATE:}
        permitted-number-of-calls-in-half-open-state: ${CIRCUITBREAKER_OPENSEARCH_PERMITTED_CALLS_IN_HALF_OPEN_STATE:}
        max-wait-duration-in-half-open-state: ${CIRCUITBREAKER_OPENSEARCH_MAX_WAIT_DURATION_IN_HALF_OPEN_STATE:}

server:
  port: 8082
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
        add-additional-paths: true
  metrics:
    tags:
      application: axon-showcase
  prometheus:
    metrics:
      export:
        enabled: false
  otlp:
    metrics:
      export:
        enabled: false
    tracing:
      export:
        enabled: false
