tempo:
  reportingEnabled: false
  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://prometheus-operated:9090/api/v1/write"
  resources:
    requests:
      cpu: 0.5
      memory: 2.0Gi
    limits:
      cpu: 0.75
      memory: 3.0Gi
  livenessProbe:
    initialDelaySeconds: 0
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
