fullnameOverride: axon-showcase-kafka

extraConfigYaml:
  num.recovery.threads.per.data.dir: 1
  default.replication.factor: 1
  offsets.topic.replication.factor: 1
  transaction.state.log.replication.factor: 1
  transaction.state.log.min.isr: 1

listeners:
  client:
    name: PLAINTEXT
    protocol: PLAINTEXT

controller:
  replicaCount: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 0.75
      memory: 1.25Gi
    limits:
      cpu: 1.0
      memory: 1.75Gi

networkPolicy:
  allowExternal: false
  allowExternalEgress: false
  ingressNSMatchLabels:
    name: monitoring
  ingressNSPodMatchLabels:
    prometheus: kps

metrics:
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: kps
  resources:
    requests:
      cpu: 0.1
      memory: 32Mi
    limits:
      cpu: 0.2
      memory: 64Mi

provisioning:
  enabled: true
  topics:
    - name: axon-showcase-events
      partitions: 8
      replicationFactor: 1
  resources:
    requests:
      cpu: 0.25
      memory: 512Mi
    limits:
      cpu: 0.5
      memory: 768Mi
