global:
  security:
    allowInsecureImages: true

fullnameOverride: axon-showcase-kafka

image:
  repository: bitnamilegacy/kafka

extraConfigYaml:
  num.recovery.threads.per.data.dir: 1
  default.replication.factor: 1
  offsets.topic.replication.factor: 1
  transaction.state.log.replication.factor: 1
  transaction.state.log.min.isr: 1

listeners:
  client:
    name: PLAINTEXT
    protocol: PLAINTEXT

controller:
  replicaCount: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 0.5
      memory: 2.0Gi
    limits:
      cpu: 0.75
      memory: 3.0Gi

networkPolicy:
  allowExternal: false
  allowExternalEgress: false
  ingressNSMatchLabels:
    name: monitoring
  ingressNSPodMatchLabels:
    prometheus: kps

metrics:
  jmx:
    enabled: true
    image:
      repository: bitnamilegacy/jmx-exporter
    resources:
      requests:
        cpu: 0.1
        memory: 96Mi
      limits:
        cpu: 0.2
        memory: 128Mi
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: kps

provisioning:
  enabled: true
  topics:
    - name: axon-showcase-events
      partitions: 8
      replicationFactor: 1
  resources:
    requests:
      cpu: 0.25
      memory: 512Mi
    limits:
      cpu: 0.5
      memory: 768Mi
