fullnameOverride: axon-showcase-kafka

extraConfig:
  num.partitions: 2
  num.recovery.threads.per.data.dir: 1
  default.replication.factor: 1
  offsets.topic.replication.factor: 1
  transaction.state.log.replication.factor: 1
  transaction.state.log.min.isr: 1

listeners:
  client:
    name: PLAINTEXT
    protocol: PLAINTEXT

controller:
  replicaCount: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 500m
      memory: 768Mi
    limits:
      cpu: 1000m
      memory: 1536Mi

networkPolicy:
  allowExternal: false
  allowExternalEgress: false
  ingressNSMatchLabels:
    name: monitoring
  ingressNSPodMatchLabels:
    prometheus: kps

metrics:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: kps
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

provisioning:
  enabled: true
  topics:
    - name: axon-showcase-events
      partitions: 2
      replicationFactor: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 768Mi
