global:
  security:
    allowInsecureImages: true

fullnameOverride: axon-showcase-os-views

image:
  repository: bitnamilegacy/opensearch

sysctlImage:
  repository: bitnamilegacy/os-shell

master:
  replicaCount: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 0.5
      memory: 1.0Gi
    limits:
      cpu: 3.0
      memory: 1.5Gi
  networkPolicy:
    allowExternal: false
    allowExternalEgress: false
    ingressNSMatchLabels:
      name: monitoring
    ingressNSPodMatchLabels:
      prometheus: kps
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      labels:
        release: kps

data:
  replicaCount: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 0.5
      memory: 2.0Gi
    limits:
      cpu: 3.0
      memory: 3.0Gi
  networkPolicy:
    allowExternal: false
    allowExternalEgress: false
    ingressNSMatchLabels:
      name: monitoring
    ingressNSPodMatchLabels:
      prometheus: kps
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      labels:
        release: kps

coordinating:
  replicaCount: 0

ingest:
  enabled: false
