spring:
  application:
    name: showcase-command-client-component-test
  main:
    banner-mode: off

resilience4j:
  retry:
    instances:
      showcase-command-service:
        max-attempts: 2
        wait-duration: PT0.01S
