fullnameOverride: axon-showcase-es-views

master:
  replicaCount: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 250m
      memory: 768Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  networkPolicy:
    allowExternal: false
    allowExternalEgress: false
    ingressNSMatchLabels:
      name: monitoring
    ingressNSPodMatchLabels:
      prometheus: kps

data:
  replicaCount: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 750m
      memory: 4Gi
  networkPolicy:
    allowExternal: false
    allowExternalEgress: false
    ingressNSMatchLabels:
      name: monitoring
    ingressNSPodMatchLabels:
      prometheus: kps

coordinating:
  replicaCount: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 250m
      memory: 1024Mi
    limits:
      cpu: 500m
      memory: 1536Mi
  networkPolicy:
    allowExternal: false
    allowExternalEgress: false
    ingressNSMatchLabels:
      name: monitoring
    ingressNSPodMatchLabels:
      prometheus: kps

ingest:
  replicaCount: 0

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: kps
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
