// SPDX-License-Identifier: MIT
package showcase.loadtests;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import lombok.val;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

@DisplayName("Baseline trend tests")
class BaselineTrendTests {

    private static final String GENERATED = """
            <!-- Generated by scripts/load-test-baseline.sh for TARGET_PLACEHOLDER; annotate before committing. -->

            # Load-test baseline: 2026-09-27

            - Target: TARGET_PLACEHOLDER
            - Target node allocatable: 10 cpu / 16341164Ki
            - Calibration: ramp to 200 workload units/s over PT5M (1 step(s))
            - Knee: not measured (no sustained departure up to the 200-unit/s calibration ceiling)
            - Operating point: 122 workload units/s (60% of the ceiling; raise CALIBRATE_MAX_RATE for a measured knee)
            - Read share: 0.75, SSE connections: 10
            - Plateau duration: PT10M

            ## Gatling summary (baseline plateau)

            ```
            > request count                        |   138,371 |   138,371 |         -
            > min response time (ms)               |         0 |         0 |         -
            > max response time (ms)               |       419 |       419 |         -
            > mean response time (ms)              |         6 |         6 |         -
            > response time 95th percentile (ms)   |         9 |         9 |         -
            > response time 99th percentile (ms)   |        14 |        14 |         -
            > mean throughput (rps)                |    229.09 |    229.09 |         -
            ```
            """;

    private static final String HAND_AUTHORED = """
            # Load-test baseline: 2026-09-26

            ## Target

            - Local Helm cluster (`./gradlew helmInstallToLocal`), reached through the gateway ingress hostname.
            - Node: **10 vCPU / ~16 GiB** (colima).

            ## Result

            - Requests: **232,080** over the 10-minute plateau (**385 rps**), 0 failed.
            - Response time: mean **5 ms**, p95 **8 ms**, p99 **11 ms**, max 442 ms.
            """;

    @Test
    @DisplayName("A generated record is parsed with its date, target, method, and plateau figures")
    void read_aGeneratedRecord_parsesItsMethodAndFigures(@TempDir Path directory) throws IOException {
        write(directory, "2026-09-27.md", generated("http://axon-showcase-api"));

        val entries = BaselineTrend.read(directory);

        assertThat(entries).singleElement().satisfies(entry -> {
            assertThat(entry.date()).hasToString("2026-09-27");
            assertThat(entry.slug()).isEmpty();
            assertThat(entry.target()).isEqualTo("http://axon-showcase-api");
            assertThat(entry.knee())
                    .isEqualTo("not measured (no sustained departure up to the 200-unit/s calibration ceiling)");
            assertThat(entry.operatingPoint())
                    .isEqualTo(
                            "122 workload units/s (60% of the ceiling; raise CALIBRATE_MAX_RATE for a measured knee)");
            assertThat(entry.plateauDuration()).isEqualTo("PT10M");
            assertThat(entry.meanMs()).isEqualTo(6);
            assertThat(entry.p95Ms()).isEqualTo(9);
            assertThat(entry.p99Ms()).isEqualTo(14);
            assertThat(entry.throughputRps()).isEqualTo(229.09);
            assertThat(entry.readable()).isTrue();
        });
    }

    @Test
    @DisplayName("A generated record with hand annotations appended is still readable")
    void read_anAnnotatedRecord_isStillReadable(@TempDir Path directory) throws IOException {
        write(
                directory,
                "2026-09-27.md",
                generated("http://axon-showcase-api") + "\n## Notes\n\nThe gateway was the busiest pod.\n");

        assertThat(BaselineTrend.read(directory)).singleElement().satisfies(entry -> assertThat(entry.readable())
                .isTrue());
    }

    @Test
    @DisplayName("A hand-authored record with no plateau figures is reported as unreadable, not fatal")
    void read_aRecordWithNoFigures_isReportedUnreadable(@TempDir Path directory) throws IOException {
        write(directory, "2026-09-26.md", HAND_AUTHORED);

        assertThat(BaselineTrend.read(directory)).singleElement().satisfies(entry -> assertThat(entry.readable())
                .isFalse());
        assertThat(BaselineTrend.report(directory)).contains("unreadable");
    }

    @Test
    @DisplayName("An empty record set is reported as nothing to trend")
    void read_anEmptyDirectory_reportsNothingToTrend(@TempDir Path directory) throws IOException {
        assertThat(BaselineTrend.read(directory)).isEmpty();
        assertThat(BaselineTrend.report(directory)).contains("nothing to trend");
    }

    @Test
    @DisplayName("Records for more than one target each name the target they measured")
    void read_multipleTargets_stayDistinguishable(@TempDir Path directory) throws IOException {
        write(directory, "2026-09-26.md", generated("http://axon-showcase-api"));
        write(directory, "2026-09-27.md", generated("http://axon-showcase-api-other"));

        assertThat(BaselineTrend.report(directory))
                .contains("http://axon-showcase-api")
                .contains("http://axon-showcase-api-other");
    }

    @Test
    @DisplayName("Records of the same day are ordered by their filename slug")
    void read_sameDayRecords_areOrderedBySlug(@TempDir Path directory) throws IOException {
        write(directory, "2026-09-26-whole-stack.md", generated("http://axon-showcase-api"));
        write(directory, "2026-09-26.md", generated("http://axon-showcase-api"));

        assertThat(BaselineTrend.read(directory))
                .extracting(BaselineTrend.Entry::slug)
                .containsExactly("", "whole-stack");
    }

    /**
     * Writes a record fixture.
     *
     * @param directory the fixture directory
     * @param name the record's filename
     * @param content the record's content
     * @throws IOException if the record cannot be written
     */
    private static void write(Path directory, String name, String content) throws IOException {
        Files.writeString(directory.resolve(name), content);
    }

    /**
     * Builds a generated-style record for a target.
     *
     * @param target the target measured
     * @return the record's content
     */
    private static String generated(String target) {
        return GENERATED.replace("TARGET_PLACEHOLDER", target);
    }
}
