fullnameOverride: axon-showcase-db-sagas

auth:
  enablePostgresUser: false
  database: showcase-sagas
  username: showcase

primary:
  extraEnvVars:
    - name: "POSTGRESQL_MAX_CONNECTIONS"
      value: "400"
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 0.5
      memory: 1.0Gi
    limits:
      cpu: 0.75
      memory: 1.5Gi
  networkPolicy:
    allowExternal: false
    allowExternalEgress: false
    ingressNSMatchLabels:
      name: monitoring
    ingressNSPodMatchLabels:
      prometheus: kps

metrics:
  enabled: true
  collectors:
    wal: false
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: kps
  resources:
    requests:
      cpu: 0.1
      memory: 16Mi
    limits:
      cpu: 0.2
      memory: 32Mi
