{
 "title": "Axon Showcase",
 "description": "Dashboard for Axon Showcase.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$application\", service=\"axon-showcase-api-gateway\", uri!~\"/actuator.*\", status!~\"5..\"}) / sum(http_server_requests_seconds_count{application=\"$application\", service=\"axon-showcase-api-gateway\", uri!~\"/actuator.*\"})",
     "legendFormat": "API"
    },
    {
     "expr": "sum(distributedCommandBus_processedCounter_total{application=\"$application\"}) / sum(distributedCommandBus_ingestedCounter_total{application=\"$application\"} - distributedCommandBus_ignoredCounter_total{application=\"$application\"})",
     "legendFormat": "Command Bus"
    },
    {
     "expr": "sum(showcaseProjector_processedCounter_total{application=\"$application\", service=\"axon-showcase-projection-service\"}) / sum(showcaseProjector_ingestedCounter_total{application=\"$application\", service=\"axon-showcase-projection-service\"} - showcaseProjector_ignoredCounter_total{application=\"$application\", service=\"axon-showcase-projection-service\"})",
     "legendFormat": "Projection"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$application\", service=\"axon-showcase-query-service\", uri!~\"/actuator.*\", status!~\"5..\"}) / sum(http_server_requests_seconds_count{application=\"$application\", service=\"axon-showcase-query-service\", uri!~\"/actuator.*\"})",
     "legendFormat": "Query Bus"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(system_cpu_usage{application=\"$application\", service=\"axon-showcase-api-gateway\"})",
     "legendFormat": "API Gateway"
    },
    {
     "expr": "max(system_cpu_usage{application=\"$application\", service=\"axon-showcase-command-service\"})",
     "legendFormat": "Command Service"
    },
    {
     "expr": "max(system_cpu_usage{application=\"$application\", service=\"axon-showcase-saga-service\"})",
     "legendFormat": "Saga Service"
    },
    {
     "expr": "max(system_cpu_usage{application=\"$application\", service=\"axon-showcase-projection-service\"})",
     "legendFormat": "Projection Service"
    },
    {
     "expr": "max(system_cpu_usage{application=\"$application\", service=\"axon-showcase-query-service\"})",
     "legendFormat": "Query Service"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$application-api-gateway-.+\"}) / sum(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"$application-api-gateway-.+\"})",
     "legendFormat": "API Gateway"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$application-command-service-.+\"}) / sum(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"$application-command-service-.+\"})",
     "legendFormat": "Command Service"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$application-saga-service-.+\"}) / sum(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"$application-saga-service-.+\"})",
     "legendFormat": "Saga Service"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$application-projection-service-.+\"}) / sum(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"$application-projection-service-.+\"})",
     "legendFormat": "Projection Service"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$application-query-service-.+\"}) / sum(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"$application-query-service-.+\"})",
     "legendFormat": "Query Service"
    }
   ]
  },
  { "title": "API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", service=\"axon-showcase-api-gateway\", uri!~\"/actuator.*\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(method, uri) (rate(http_server_requests_seconds_count{application=\"$application\", service=\"axon-showcase-api-gateway\", uri!~\"/actuator.*\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{application=\"$application\", service=\"axon-showcase-api-gateway\", uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{application=\"$application\", service=\"axon-showcase-api-gateway\", uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by(method, uri) (rate(http_server_requests_seconds_sum{application=\"$application\", service=\"axon-showcase-api-gateway\", uri!~\"/actuator.*\"}[1m])) / sum by(method, uri) (rate(http_server_requests_seconds_count{application=\"$application\", service=\"axon-showcase-api-gateway\", uri!~\"/actuator.*\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", service=\"axon-showcase-api-gateway\", uri!~\"/actuator.*\", status=~\"4..|5..\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(status, method, uri) (rate(http_server_requests_seconds_count{application=\"$application\", service=\"axon-showcase-api-gateway\", uri!~\"/actuator.*\", status=~\"4..|5..\"}[1m]))",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Fallback Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by (name) (rate(cache_gets_total{application=\"$application\", service=\"axon-showcase-api-gateway\", result=\"hit\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Command Bus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(distributedCommandBus_ingestedCounter_total{application=\"$application\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (payloadType) (rate(distributedCommandBus_ingestedCounter_total{application=\"$application\"}[1m]))",
     "legendFormat": "{{payloadType}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(distributedCommandBus_allTimer_seconds_bucket{application=\"$application\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(distributedCommandBus_allTimer_seconds_bucket{application=\"$application\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by(payloadType) (rate(distributedCommandBus_allTimer_seconds_sum{application=\"$application\"}[1m])) / sum by(payloadType) (rate(distributedCommandBus_allTimer_seconds_count{application=\"$application\"}[1m]))",
     "legendFormat": "{{payloadType}}"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(distributedCommandBus_failureCounter_total{application=\"$application\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (payloadType) (rate(distributedCommandBus_failureCounter_total{application=\"$application\"}[1m]))",
     "legendFormat": "{{payloadType}}"
    }
   ]
  },
  { "title": "Command Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Command Handling Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(commandBus_successCounter_total{application=\"$application\", service=\"axon-showcase-command-service\"}[1m]))",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum by (payloadType) (rate(commandBus_failureCounter_total{application=\"$application\", service=\"axon-showcase-command-service\"}[1m]))",
     "legendFormat": "Failed {{payloadType}}"
    }
   ]
  },
  {
   "title": "Command Handling Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(commandBus_allTimer_seconds_bucket{application=\"$application\", service=\"axon-showcase-command-service\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(commandBus_allTimer_seconds_bucket{application=\"$application\", service=\"axon-showcase-command-service\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by(payloadType) (rate(commandBus_allTimer_seconds_sum{application=\"$application\", service=\"axon-showcase-command-service\"} [1m])) / sum by(payloadType) (rate(commandBus_allTimer_seconds_count{application=\"$application\", service=\"axon-showcase-command-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Storing Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(eventStore_successCounter_total{application=\"$application\", service=\"axon-showcase-command-service\"}[1m]))",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum by (payloadType) (rate(eventStore_failureCounter_total{application=\"$application\", service=\"axon-showcase-command-service\"}[1m]))",
     "legendFormat": "Failed {{payloadType}}"
    }
   ]
  },
  {
   "title": "Event Storing Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(eventStore_allTimer_seconds_bucket{application=\"$application\", service=\"axon-showcase-command-service\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(eventStore_allTimer_seconds_bucket{application=\"$application\", service=\"axon-showcase-command-service\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by(payloadType) (rate(eventStore_allTimer_seconds_sum{application=\"$application\", service=\"axon-showcase-command-service\"} [1m])) / sum by(payloadType) (rate(eventStore_allTimer_seconds_count{application=\"$application\", service=\"axon-showcase-command-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saga Event Handling Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum(rate(eventProcessor_successCounter_total{application=\"$application\", service=\"axon-showcase-command-service\", processorName=\"showcase-saga\"}[1m]))",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum by (payloadType) (rate(eventProcessor_failureCounter_total{application=\"$application\", service=\"axon-showcase-command-service\", processorName=\"showcase-saga\"}[1m]))",
     "legendFormat": "Failed {{payloadType}}"
    }
   ]
  },
  {
   "title": "Saga Event Handling Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(eventProcessor_allTimer_seconds_bucket{application=\"$application\", service=\"axon-showcase-command-service\", processorName=\"showcase-saga\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(eventProcessor_allTimer_seconds_bucket{application=\"$application\", service=\"axon-showcase-command-service\", processorName=\"showcase-saga\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by(payloadType) (rate(eventProcessor_allTimer_seconds_sum{application=\"$application\", service=\"axon-showcase-command-service\", processorName=\"showcase-saga\"} [1m])) / sum by(payloadType) (rate(eventProcessor_allTimer_seconds_count{application=\"$application\", service=\"axon-showcase-command-service\", processorName=\"showcase-saga\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadline Handling Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(dbscheduler_executionLag_seconds_bucket{application=\"$application\", service=\"axon-showcase-command-service\", task=\"AxonDeadline\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(dbscheduler_executionLag_seconds_bucket{application=\"$application\", service=\"axon-showcase-command-service\", task=\"AxonDeadline\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by(deadline) (rate(dbscheduler_executionLag_seconds_sum{application=\"$application\", service=\"axon-showcase-command-service\", task=\"AxonDeadline\"}[1m])) / sum by (deadline) (rate(dbscheduler_executionLag_seconds_count{application=\"$application\", service=\"axon-showcase-command-service\", task=\"AxonDeadline\"}[1m]))",
     "legendFormat": "{{deadline}}"
    }
   ]
  },
  {
   "title": "Deadline Handling Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(dbscheduler_executions_total{application=\"$application\", service=\"axon-showcase-command-service\", task=\"AxonDeadline\", result=\"ok\"}[1m]))",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum by (deadline, error) (rate(dbscheduler_executions_total{application=\"$application\", service=\"axon-showcase-command-service\", task=\"AxonDeadline\", result=\"failed\"}[1m]))",
     "legendFormat": "Failed {{deadline}} {{error}}"
    }
   ]
  },
  {
   "title": "Deadline Handling Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(dbscheduler_executionDuration_seconds_bucket{application=\"$application\", service=\"axon-showcase-command-service\", task=\"AxonDeadline\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(dbscheduler_executionDuration_seconds_bucket{application=\"$application\", service=\"axon-showcase-command-service\", task=\"AxonDeadline\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by (deadline) (rate(dbscheduler_executionDuration_seconds_sum{application=\"$application\", service=\"axon-showcase-command-service\", task=\"AxonDeadline\"}[1m])) / sum by (deadline) (rate(dbscheduler_executionDuration_seconds_count{application=\"$application\", service=\"axon-showcase-command-service\", task=\"AxonDeadline\"}[1m]))",
     "legendFormat": "{{deadline}}"
    }
   ]
  },
  {
   "title": "Event Publishing Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(rate(eventProcessor_successCounter_total{application=\"$application\", service=\"axon-showcase-command-service\", processorName=\"event-publishing\"}[1m]))",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum by (payloadType) (rate(eventProcessor_failureTimer_seconds_count{application=\"$application\", service=\"axon-showcase-command-service\", processorName=\"event-publishing\"}[1m]))",
     "legendFormat": "Failed {{payloadType}}"
    }
   ]
  },
  {
   "title": "Event Publishing Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(eventProcessor_allTimer_seconds_bucket{application=\"$application\", service=\"axon-showcase-command-service\", processorName=\"event-publishing\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(eventProcessor_allTimer_seconds_bucket{application=\"$application\", service=\"axon-showcase-command-service\", processorName=\"event-publishing\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by(payloadType) (rate(eventProcessor_allTimer_seconds_sum{application=\"$application\", service=\"axon-showcase-command-service\", processorName=\"event-publishing\"} [1m])) / sum by(payloadType) (rate(eventProcessor_allTimer_seconds_count{application=\"$application\", service=\"axon-showcase-command-service\", processorName=\"event-publishing\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "sum by(cache) (rate(cache_gets_total{application=\"$application\", service=\"axon-showcase-command-service\", result=\"hit\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "sum by(cache) (rate(cache_gets_total{application=\"$application\", service=\"axon-showcase-command-service\", result=\"miss\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Projection Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Projection Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(showcaseProjector_projectionLag_seconds_bucket{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(showcaseProjector_projectionLag_seconds_bucket{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by(payloadType) (rate(showcaseProjector_projectionLag_seconds_sum{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m])) / sum by(payloadType) (rate(showcaseProjector_projectionLag_seconds_count{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "sum(rate(showcaseProjector_ingestedCounter_total{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (payloadType) (rate(showcaseProjector_ingestedCounter_total{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m]))",
     "legendFormat": "{{payloadType}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(showcaseProjector_allTimer_seconds_bucket{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(showcaseProjector_allTimer_seconds_bucket{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by(payloadType) (rate(showcaseProjector_allTimer_seconds_sum{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m])) / sum by(payloadType) (rate(showcaseProjector_allTimer_seconds_count{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(showcaseProjector_batch_size_events_sum{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m])) / sum(rate(showcaseProjector_batch_size_events_count{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(showcaseProjector_batch_size_events_bucket{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(showcaseProjector_batch_size_events_bucket{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(showcaseProjector_batch_size_events_bucket{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m])))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "sum(rate(showcaseProjector_failureCounter_total{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (payloadType) (rate(showcaseProjector_failureCounter_total{application=\"$application\", service=\"axon-showcase-projection-service\"}[1m]))",
     "legendFormat": "{{payloadType}}"
    },
    {
     "expr": "sum by (error) (rate(project_showcase_seconds_count{application=\"$application\", service=\"axon-showcase-projection-service\", error!=\"none\"}[1m]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  { "title": "Query Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", service=\"axon-showcase-query-service\", uri!~\"/actuator.*\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(fetch_showcase_list_seconds_count{application=\"$application\", service=\"axon-showcase-query-service\"}[1m]))",
     "legendFormat": "FetchShowcaseListQuery"
    },
    {
     "expr": "sum(rate(fetch_showcase_by_id_seconds_count{application=\"$application\", service=\"axon-showcase-query-service\"}[1m]))",
     "legendFormat": "FetchShowcaseByIdQuery"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{application=\"$application\", service=\"axon-showcase-query-service\", uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{application=\"$application\", service=\"axon-showcase-query-service\", uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(fetch_showcase_list_seconds_sum[1m])) / sum(rate(fetch_showcase_list_seconds_count[1m]))",
     "legendFormat": "FetchShowcaseListQuery"
    },
    {
     "expr": "sum(rate(fetch_showcase_by_id_seconds_sum[1m])) / sum(rate(fetch_showcase_by_id_seconds_count[1m]))",
     "legendFormat": "FetchShowcaseByIdQuery"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "sum(rate(fetch_showcase_list_seconds_count{application=\"$application\", service=\"axon-showcase-query-service\", error!=\"none\"}[1m])) + sum(rate(fetch_showcase_by_id_seconds_count{application=\"$application\", service=\"axon-showcase-query-service\", error!=\"none\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (error) (rate(fetch_showcase_list_seconds_count{application=\"$application\", service=\"axon-showcase-query-service\", error!=\"none\"}[1m])) + sum by (error) (rate(fetch_showcase_by_id_seconds_count{application=\"$application\", service=\"axon-showcase-query-service\", error!=\"none\"}[1m]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  { "title": "Web UI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{service=\"axon-showcase-web-ui\"}[1m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nginx_connections_active{service=\"axon-showcase-web-ui\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Connection States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nginx_connections_reading{service=\"axon-showcase-web-ui\"})",
     "legendFormat": "Reading"
    },
    {
     "expr": "sum(nginx_connections_writing{service=\"axon-showcase-web-ui\"})",
     "legendFormat": "Writing"
    },
    {
     "expr": "sum(nginx_connections_waiting{service=\"axon-showcase-web-ui\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Accepted / Handled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_accepted{service=\"axon-showcase-web-ui\"}[1m]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(rate(nginx_connections_handled{service=\"axon-showcase-web-ui\"}[1m]))",
     "legendFormat": "Handled"
    }
   ]
  }
 ]
}