fullnameOverride: kps

cleanPrometheusOperatorObjectNames: true

alertmanager:
  enabled: false

kube-state-metrics:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

nodeExporter:
  enabled: false

kubernetesServiceMonitors:
  enabled: true

grafana:
  defaultDashboardsEnabled: false
  additionalDataSources:
    - name: Tempo
      access: proxy
      type: tempo
      url: http://tempo:3200
  resources:
    requests:
      cpu: 250m
      memory: 0.5Gi
    limits:
      cpu: 500m
      memory: 0.75Gi
  serviceMonitor:
    enabled: false
  sidecar:
    datasources:
      alertmanager:
        enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 160Mi

prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 250m
        memory: 1.0Gi
      limits:
        cpu: 500m
        memory: 1.5Gi
  serviceMonitor:
    selfMonitor: false

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  prometheusConfigReloader:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 64Mi
  serviceMonitor:
    selfMonitor: false
