fullnameOverride: kps

cleanPrometheusOperatorObjectNames: true

alertmanager:
  enabled: false

kube-state-metrics:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi

nodeExporter:
  enabled: false

kubernetesServiceMonitors:
  enabled: true

grafana:
  defaultDashboardsEnabled: false
  additionalDataSources:
    - name: Tempo
      access: proxy
      type: tempo
      url: http://tempo:3200
  ingress:
    enabled: true
    hosts:
      - axon-showcase-grafana
  resources:
    requests:
      cpu: 50m
      memory: 0.75Gi
    limits:
      memory: 1Gi
  serviceMonitor:
    enabled: false
  sidecar:
    datasources:
      alertmanager:
        enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 160Mi

prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 100m
        memory: 1.5Gi
      limits:
        memory: 2Gi
  serviceMonitor:
    selfMonitor: false

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
  prometheusConfigReloader:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
  serviceMonitor:
    selfMonitor: false
