spring:
  application:
    name: axon-showcase-query-service
  main:
    banner-mode: off
  data:
    elasticsearch:
      repositories:
        enabled: off
  jackson:
    default-property-inclusion: non_null
  web:
    locale: en
  webflux:
    problemdetails:
      enabled: true
  reactor:
    context-propagation: auto
  threads:
    virtual:
      enabled: true

axon:
  serializer:
    messages: jackson
  metrics:
    micrometer:
      dimensional: true
  tracing:
    repository:
      aggregate-id-attribute-name: axon.aggregateId

opensearch:
  uris: ${OS_URIS:http://localhost:9200}
  username: ${OS_USER:elastic}
  password: ${OS_PASSWORD:}
  connection-timeout: ${OS_CONNECTION_TIMEOUT:PT1S}
  socket-timeout: ${OS_SOCKET_TIMEOUT:PT2S}
  socket-keep-alive: ${OS_SOCKET_KEEP_ALIVE:false}
  max-connections: ${OS_MAX_CONNECTIONS:1000}
  max-connections-per-route: ${OS_MAX_CONNECTIONS_PER_ROUTE:100}
  evict-expired-connections: ${OS_EVICT_EXPIRED_CONNECTIONS:true}
  evict-idle-connections: ${OS_EVICT_IDLE_CONNECTIONS:PT2S}

showcase:
  query:
    index-initialization-enabled: ${INDEX_INITIALIZATION_ENABLED:true}
    exit-after-index-initialization: ${EXIT_AFTER_INDEX_INITIALIZATION:false}

server:
  port: 8084
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: on
        add-additional-paths: on
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: ${METRICS_PERCENTILES_HISTOGRAM:true}
        http.client.requests: ${METRICS_PERCENTILES_HISTOGRAM:true}
      percentiles:
        http.server.requests: ${METRICS_PERCENTILES:0.5, 0.75, 0.95, 0.98, 0.99, 0.995, 0.999}
        http.client.requests: ${METRICS_PERCENTILES:0.5, 0.75, 0.95, 0.98, 0.99, 0.995, 0.999}
      slo:
        http.server.requests: ${METRICS_SLO:100ms, 200ms, 300ms, 400ms, 500ms, 1s, 2s, 3s, 4s, 5s}
        http.client.requests: ${METRICS_SLO:100ms, 200ms, 300ms, 400ms, 500ms, 1s, 2s, 3s, 4s, 5s}
    tags:
      application: axon-showcase
  prometheus:
    metrics:
      export:
        enabled: false
  otlp:
    metrics:
      export:
        enabled: false
    tracing:
      export:
        enabled: false
