spring:
  application:
    name: axon-showcase-query-service
  main:
    banner-mode: off
  elasticsearch:
    uris: ${ES_URIS:http://localhost:9200}
    username: ${ES_USER:elastic}
    password: ${ES_PASSWORD:}
    connection-timeout: ${ES_CONNECTION_TIMEOUT:PT1S}
    socket-timeout: ${ES_SOCKET_TIMEOUT:PT30S}
    socket-keep-alive: ${ES_SOCKET_KEEP_ALIVE:false}
  web:
    locale: en
  webflux:
    problemdetails:
      enabled: on
  threads:
    virtual:
      enabled: true

axon:
  serializer:
    messages: jackson
  metrics:
    micrometer:
      dimensional: true

showcase:
  query:
    index-initialization-enabled: ${INDEX_INITIALIZATION_ENABLED:true}
    exit-after-index-initialization: ${EXIT_AFTER_INDEX_INITIALIZATION:false}
    metrics:
      tags:
        - key: ${METRICS_TAG_APPLICATION_KEY:application}
          value: ${METRICS_TAG_APPLICATION_VALUE:axon-showcase}
    tracing:
      logging: ${TRACING_LOGGING:false}

server:
  port: 8084
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: on
        add-additional-paths: on
    prometheus:
      enabled: ${METRICS_PROMETHEUS_ENABLED:false}
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: ${METRICS_PERCENTILES_HISTOGRAM:true}
        http.client.requests: ${METRICS_PERCENTILES_HISTOGRAM:true}
      percentiles:
        http.server.requests: ${METRICS_PERCENTILES:0.5, 0.75, 0.95, 0.98, 0.99, 0.995, 0.999}
        http.client.requests: ${METRICS_PERCENTILES:0.5, 0.75, 0.95, 0.98, 0.99, 0.995, 0.999}
      slo:
        http.server.requests: ${METRICS_SLO:100ms, 200ms, 300ms, 400ms, 500ms, 1s, 2s, 3s, 4s, 5s}
        http.client.requests: ${METRICS_SLO:100ms, 200ms, 300ms, 400ms, 500ms, 1s, 2s, 3s, 4s, 5s}
    export:
      prometheus:
        enabled: ${METRICS_PROMETHEUS_ENABLED:false}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      export:
        enabled: ${TRACING_OTLP_ENABLED:false}
      endpoint: ${TRACING_OTLP_ENDPOINT:}
