resilience4j:
  enabled: true
  timelimiter:
    enabled: false
  circuitbreaker:
    enabled: false
  retry:
    instances:
      showcase-query-service:
        max-attempts: 2
        wait-duration: PT0.01S
