global:
  imageRegistry: ""
  imagePullSecrets: [ ]

kubeVersion: ""

nameOverride: ""

fullnameOverride: ""

namespaceOverride: ""

clusterDomain: cluster.local

extraDeploy: [ ]

commonLabels: { }

commonAnnotations: { }

dbEvents:
  hosts: axon-showcase-db-events
  name: showcase-events
  schema: public
  params: ""
  username: showcase
  passwordSecret:
    name: axon-showcase-db-events
    key: password

osViews:
  uris: http://axon-showcase-os-views:9200
  secured: false
  passwordSecret:
    name: axon-showcase-os-views
    key: elasticsearch-password

kafka:
  bootstrapServers: axon-showcase-kafka:9092
  topics:
    events: axon-showcase-events
  securityProtocol: PLAINTEXT

commandService:

  labels: { }

  annotations: { }

  podLabels: { }

  podAnnotations: { }

  image:
    registry: ""
    repository: aanbrn/axon-showcase-command-service
    tag: ${projectVersion}
    digest: ""
    pullPolicy: null
    pullSecrets: [ ]

  replicaCount: 1

  revisionHistoryLimit: 10

  updateStrategy:
    type: RollingUpdate

  dbEvents:
    pool:
      maxSize: 100
      minIdle: 20
      maxLifetime: 1800000
      connectionTimeout: 30000
      validationTimeout: 5000
      idleTimeout: 600000
      leakDetectionThreshold: 0

  kafka:
    producer:
      retries: 3

  showcaseCache:
    maxSize: 100000
    expiresAfterAccess: PT10M
    expiresAfterWrite: PT5M

  extraEnvVars:
    JAVA_OPTS: "-XX:MaxDirectMemorySize=128M -XX:MaxGCPauseMillis=20"

  extraEnvVarsCM: ""

  extraEnvVarsSecret: ""

  containerPorts:
    server: 8080
    managementServer: 8888
    jgroups: 7800

  extraContainerPorts: [ ]

  startupProbe:
    enabled: true
    initialDelaySeconds: 3
    periodSeconds: 3
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  resources:
    requests:
      cpu: 1.0
      memory: 0.5Gi
    limits:
      cpu: 3.0
      memory: 1Gi

  lifecycleHooks: { }

  affinity: { }

  podAffinityPreset: ""

  podAntiAffinityPreset: soft

  nodeAffinityPreset:
    type: ""
    key: ""
    values: [ ]

  automountServiceAccountToken: true

  hostAliases: [ ]

  nodeSelector: { }

  tolerations: [ ]

  priorityClassName: ""

  schedulerName: ""

  topologySpreadConstraints: [ ]

  terminationGracePeriodSeconds: ""

  terminationMessagePolicy: FallbackToLogsOnError

  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: [ ]
    supplementalGroups: [ ]
    fsGroup: 1001

  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  extraVolumeMounts: [ ]

  extraVolumes: [ ]

  initContainers: [ ]

  sidecars: [ ]

  extraPodSpec: { }

  autoscaling:
    vpa:
      enabled: false
      controlledResources: [ ]
      maxAllowed: { }
      minAllowed: { }
      updatePolicy:
        updateMode: Auto
    hpa:
      enabled: false
      minReplicas: 3
      maxReplicas: 5
      targetCPU: 80
      targetMemory: ""
      metrics: [ ]

  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""

  networkPolicy:
    enabled: true
    addExternalClientAccess: true
    ingressPodMatchLabels: { }
    ingressManagementNSMatchLabels: { }
    ingressManagementNSPodMatchLabels: { }
    extraIngress: [ ]
    extraEgress: [ ]

  serviceMonitor:
    enabled: true
    namespace: ""
    labels: { }
    annotations: { }
    interval: ""
    scrapeTimeout: ""
    relabelings: [ ]
    metricRelabelings: [ ]
    honorLabels: false

queryService:

  labels: { }

  annotations: { }

  podLabels: { }

  podAnnotations: { }

  image:
    registry: ""
    repository: aanbrn/axon-showcase-query-service
    tag: ${projectVersion}
    digest: ""
    pullPolicy: null
    pullSecrets: [ ]

  replicaCount: 1

  revisionHistoryLimit: 10

  updateStrategy:
    type: RollingUpdate

  osViews:
    connectionTimeout: PT1S
    socketTimeout: PT2S
    socketKeepAlive: true
    maxConnections: 100
    maxConnectionsPerRoute: 100
    evictIdleConnections: PT5S

  extraEnvVars:
    JAVA_OPTS: "-XX:MaxDirectMemorySize=128M -XX:MaxGCPauseMillis=20"

  extraEnvVarsCM: ""

  extraEnvVarsSecret: ""

  containerPorts:
    server: 8080
    managementServer: 8888

  extraContainerPorts: [ ]

  startupProbe:
    enabled: true
    initialDelaySeconds: 3
    periodSeconds: 3
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  resources:
    requests:
      cpu: 1.0
      memory: 0.5Gi
    limits:
      cpu: 3.0
      memory: 1Gi

  lifecycleHooks: { }

  affinity: { }

  podAffinityPreset: ""

  podAntiAffinityPreset: soft

  nodeAffinityPreset:
    type: ""
    key: ""
    values: [ ]

  automountServiceAccountToken: true

  hostAliases: [ ]

  nodeSelector: { }

  tolerations: [ ]

  priorityClassName: ""

  schedulerName: ""

  topologySpreadConstraints: [ ]

  terminationGracePeriodSeconds: ""

  terminationMessagePolicy: FallbackToLogsOnError

  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: [ ]
    supplementalGroups: [ ]
    fsGroup: 1001

  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  extraVolumeMounts: [ ]

  extraVolumes: [ ]

  initContainers: [ ]

  sidecars: [ ]

  extraPodSpec: { }

  autoscaling:
    vpa:
      enabled: false
      controlledResources: [ ]
      maxAllowed: { }
      minAllowed: { }
      updatePolicy:
        updateMode: Auto
    hpa:
      enabled: false
      minReplicas: 3
      maxReplicas: 5
      targetCPU: 80
      targetMemory: ""
      metrics: [ ]

  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""

  networkPolicy:
    enabled: true
    addExternalClientAccess: true
    ingressPodMatchLabels: { }
    ingressManagementNSMatchLabels: { }
    ingressManagementNSPodMatchLabels: { }
    extraIngress: [ ]
    extraEgress: [ ]

  serviceMonitor:
    enabled: true
    namespace: ""
    labels: { }
    annotations: { }
    interval: ""
    scrapeTimeout: ""
    relabelings: [ ]
    metricRelabelings: [ ]
    honorLabels: false

projectionService:

  labels: { }

  annotations: { }

  podLabels: { }

  podAnnotations: { }

  image:
    registry: ""
    repository: aanbrn/axon-showcase-projection-service
    tag: ${projectVersion}
    digest: ""
    pullPolicy: null
    pullSecrets: [ ]

  replicaCount: 1

  revisionHistoryLimit: 10

  updateStrategy:
    type: RollingUpdate

  osViews:
    connectionTimeout: PT10S
    socketTimeout: PT30S
    socketKeepAlive: true
    maxConnections: 100
    maxConnectionsPerRoute: 100
    evictIdleConnections: PT5S

  projector:
    minConcurrency: 1
    maxConcurrency: 256
    batch:
      maxSize: 100
      maxTime: PT0.1S
      bufferMaxSize: 10000
    retry:
      maxAttempts: 3
      minBackoff: PT0.1S
    restart:
      delay: PT10S

  extraEnvVars:
    JAVA_OPTS: "-XX:MaxDirectMemorySize=128M -XX:MaxGCPauseMillis=20"

  extraEnvVarsCM: ""

  extraEnvVarsSecret: ""

  containerPorts:
    server: 8080
    managementServer: 8888

  extraContainerPorts: [ ]

  startupProbe:
    enabled: true
    initialDelaySeconds: 3
    periodSeconds: 3
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  resources:
    requests:
      cpu: 1.0
      memory: 0.5Gi
    limits:
      cpu: 3.0
      memory: 0.75Gi

  lifecycleHooks: { }

  affinity: { }

  podAffinityPreset: ""

  podAntiAffinityPreset: soft

  nodeAffinityPreset:
    type: ""
    key: ""
    values: [ ]

  automountServiceAccountToken: true

  hostAliases: [ ]

  nodeSelector: { }

  tolerations: [ ]

  priorityClassName: ""

  schedulerName: ""

  topologySpreadConstraints: [ ]

  terminationGracePeriodSeconds: ""

  terminationMessagePolicy: FallbackToLogsOnError

  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: [ ]
    supplementalGroups: [ ]
    fsGroup: 1001

  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  extraVolumeMounts: [ ]

  extraVolumes: [ ]

  initContainers: [ ]

  sidecars: [ ]

  extraPodSpec: { }

  autoscaling:
    vpa:
      enabled: false
      controlledResources: [ ]
      maxAllowed: { }
      minAllowed: { }
      updatePolicy:
        updateMode: Auto
    hpa:
      enabled: false
      minReplicas: 3
      maxReplicas: 5
      targetCPU: 80
      targetMemory: ""
      metrics: [ ]

  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""

  networkPolicy:
    enabled: true
    addExternalClientAccess: true
    ingressPodMatchLabels: { }
    ingressManagementNSMatchLabels: { }
    ingressManagementNSPodMatchLabels: { }
    extraIngress: [ ]
    extraEgress: [ ]

  serviceMonitor:
    enabled: true
    namespace: ""
    labels: { }
    annotations: { }
    interval: ""
    scrapeTimeout: ""
    relabelings: [ ]
    metricRelabelings: [ ]
    honorLabels: false

apiGateway:

  labels: { }

  annotations: { }

  podLabels: { }

  podAnnotations: { }

  image:
    registry: ""
    repository: aanbrn/axon-showcase-api-gateway
    tag: ${projectVersion}
    digest: ""
    pullPolicy: null
    pullSecrets: [ ]

  replicaCount: 1

  revisionHistoryLimit: 10

  updateStrategy:
    type: RollingUpdate

  caches:
    FetchShowcaseListQuery:
      maxSize: 100000
      expiresAfterAccess: PT24H
      expiresAfterWrite: PT12H
    FetchShowcaseByIdQuery:
      maxSize: 1000000
      expiresAfterAccess: PT24H
      expiresAfterWrite: PT12H

  extraEnvVars:
    JAVA_OPTS: "-XX:MaxDirectMemorySize=128M -XX:MaxGCPauseMillis=20"

  extraEnvVarsCM: ""

  extraEnvVarsSecret: ""

  containerPorts:
    server: 8080
    managementServer: 8888
    jgroups: 7800

  extraContainerPorts: [ ]

  startupProbe:
    enabled: true
    initialDelaySeconds: 3
    periodSeconds: 3
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  resources:
    requests:
      cpu: 1.0
      memory: 0.5Gi
    limits:
      cpu: 3.0
      memory: 1Gi

  lifecycleHooks: { }

  affinity: { }

  podAffinityPreset: ""

  podAntiAffinityPreset: soft

  nodeAffinityPreset:
    type: ""
    key: ""
    values: [ ]

  automountServiceAccountToken: true

  hostAliases: [ ]

  nodeSelector: { }

  tolerations: [ ]

  priorityClassName: ""

  schedulerName: ""

  topologySpreadConstraints: [ ]

  terminationGracePeriodSeconds: ""

  terminationMessagePolicy: FallbackToLogsOnError

  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: [ ]
    supplementalGroups: [ ]
    fsGroup: 1001

  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  extraVolumeMounts: [ ]

  extraVolumes: [ ]

  initContainers: [ ]

  sidecars: [ ]

  extraPodSpec: { }

  resilience:
    enabled: true
    timelimiter:
      enabled: true
      defaults:
        timeoutDuration: PT1S
      commandService:
        timeoutDuration: ""
      queryService:
        timeoutDuration: ""
    circuitbreaker:
      enabled: true
      defaults:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 100
        minimumNumberOfCalls: 50
        failureRateThreshold: 50
        slowCallRateThreshold: 90
        slowCallDurationThreshold: PT5S
        waitDurationInOpenState: PT10S
        exponentialBackoffMultiplier: 1.5
        exponentialMaxWaitDurationInOpenState: ""
        permittedNumberOfCallsInHalfOpenState: 10
        maxWaitDurationInHalfOpenState: PT0S
      commandService:
        slidingWindowType: ""
        slidingWindowSize: ""
        minimumNumberOfCalls: ""
        failureRateThreshold: ""
        slowCallRateThreshold: ""
        slowCallDurationThreshold: ""
        waitDurationInOpenState: ""
        exponentialBackoffMultiplier: ""
        exponentialMaxWaitDurationInOpenState: ""
        permittedNumberOfCallsInHalfOpenState: ""
        maxWaitDurationInHalfOpenState: ""
      queryService:
        slidingWindowType: ""
        slidingWindowSize: ""
        minimumNumberOfCalls: ""
        failureRateThreshold: ""
        slowCallRateThreshold: ""
        slowCallDurationThreshold: ""
        waitDurationInOpenState: ""
        exponentialBackoffMultiplier: ""
        exponentialMaxWaitDurationInOpenState: ""
        permittedNumberOfCallsInHalfOpenState: ""
        maxWaitDurationInHalfOpenState: ""
    retry:
      enabled: true
      defaults:
        maxAttempts: 2
        waitDuration: PT0.5S
        exponentialBackoffMultiplier: 1.5
        randomizedWaitFactor: 0.5
        exponentialMaxWaitDuration: ""
      commandService:
        maxAttempts: ""
        waitDuration: ""
        exponentialBackoffMultiplier: ""
        randomizedWaitFactor: ""
        exponentialMaxWaitDuration: ""
      queryService:
        maxAttempts: ""
        waitDuration: ""
        exponentialBackoffMultiplier: ""
        randomizedWaitFactor: ""
        exponentialMaxWaitDuration: ""

  autoscaling:
    vpa:
      enabled: false
      controlledResources: [ ]
      maxAllowed: { }
      minAllowed: { }
      updatePolicy:
        updateMode: Auto
    hpa:
      enabled: false
      minReplicas: 3
      maxReplicas: 5
      targetCPU: 80
      targetMemory: ""
      metrics: [ ]

  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""

  networkPolicy:
    enabled: true
    addExternalClientAccess: true
    ingressPodMatchLabels: { }
    ingressManagementNSMatchLabels: { }
    ingressManagementNSPodMatchLabels: { }
    extraIngress: [ ]
    extraEgress: [ ]

  serviceMonitor:
    enabled: true
    namespace: ""
    labels: { }
    annotations: { }
    interval: ""
    scrapeTimeout: ""
    relabelings: [ ]
    metricRelabelings: [ ]
    honorLabels: false

  ingress:
    enabled: false
    ingressClassName: ""
    hostname: ""
    path: /
    pathType: Prefix
    extraPaths: [ ]
    extraHosts: [ ]
    extraRules: [ ]

  route:
    enabled: false
    labels: { }
    annotations: { }
    hostnames: [ ]
    parentRefs: [ ]
    matches:
      - path:
          type: PathPrefix
          value: /
    filters: [ ]
    extraRules: [ ]

observability:
  logging:
    structured:
      enabled: false
      format: ecs
  tracing:
    sampling:
      probability: 0.1
  prometheus:
    metrics:
      export:
        enabled: false
  otlp:
    metrics:
      export:
        enabled: false
        endpoint: ""
        step: PT30S
    tracing:
      export:
        enabled: false
        endpoint: ""
        compression: none

serviceAccount:

  create: true

  name: ""

  labels: { }

  annotations: { }

  automountServiceAccountToken: true

rbac:
  create: true
  rules: [ ]
