{{- if and .Values.sagaService.autoscaling.vpa.enabled }}
{{- $labels := include "common.tplvalues.merge" (dict "values" (list .Values.sagaService.labels .Values.commonLabels) "context" $) }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "axon-showcase.saga-service.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" $labels "context" $) | nindent 4 }}
    app.kubernetes.io/component: saga-service
  {{- if or .Values.sagaService.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.sagaService.annotations .Values.commonAnnotations) "context" $) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: main
      {{- with .Values.sagaService.autoscaling.vpa.controlledResources }}
        controlledResources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sagaService.autoscaling.vpa.maxAllowed }}
        maxAllowed:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sagaService.autoscaling.vpa.minAllowed }}
        minAllowed:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  targetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" $ }}
    kind: Deployment
    name: {{ include "axon-showcase.saga-service.fullname" $ }}
  {{- if .Values.sagaService.autoscaling.vpa.updatePolicy.updateMode }}
  updatePolicy:
    updateMode: {{ .Values.sagaService.autoscaling.vpa.updatePolicy.updateMode }}
  {{- end }}
{{- end }}
