{{- if .Values.projectionService.pdb.create }}
{{- $labels := include "common.tplvalues.merge" (dict "values" (list .Values.projectionService.labels .Values.commonLabels) "context" $) }}
{{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.projectionService.podLabels .Values.commonLabels) "context" $) }}
apiVersion: {{ include "common.capabilities.policy.apiVersion" $ }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "axon-showcase.projection-service.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" $labels "context" $) | nindent 4 }}
    app.kubernetes.io/component: projection-service
  {{- if or .Values.projectionService.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.projectionService.annotations .Values.commonAnnotations) "context" $) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.projectionService.pdb.minAvailable }}
  minAvailable: {{ .Values.projectionService.pdb.minAvailable }}
  {{- end  }}
  {{- if or .Values.projectionService.pdb.maxUnavailable ( not .Values.projectionService.pdb.minAvailable ) }}
  maxUnavailable: {{ .Values.projectionService.pdb.maxUnavailable | default 1 }}
  {{- end  }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" $) | nindent 6 }}
      app.kubernetes.io/component: projection-service
{{- end }}
