fullnameOverride: axon-showcase

commandService:
  podLabels:
    axon-showcase-db-events-client: "true"
    axon-showcase-kafka-client: "true"
  networkPolicy:
    ingressManagementNSMatchLabels:
      name: monitoring
    ingressManagementNSPodMatchLabels:
      prometheus: kps
  serviceMonitor:
    namespace: monitoring
    labels:
      release: kps

sagaService:
  kafka:
    fetcher:
      consumerCount: 8
  podLabels:
    axon-showcase-db-sagas-client: "true"
    axon-showcase-kafka-client: "true"
  networkPolicy:
    ingressManagementNSMatchLabels:
      name: monitoring
    ingressManagementNSPodMatchLabels:
      prometheus: kps
  serviceMonitor:
    namespace: monitoring
    labels:
      release: kps

projectionService:
  kafka:
    fetcher:
      consumerCount: 8
  podLabels:
    axon-showcase-kafka-client: "true"
    axon-showcase-os-views-client: "true"
    axon-showcase-redis-client: "true"
  networkPolicy:
    ingressManagementNSMatchLabels:
      name: monitoring
    ingressManagementNSPodMatchLabels:
      prometheus: kps
  serviceMonitor:
    namespace: monitoring
    labels:
      release: kps

queryService:
  podLabels:
    axon-showcase-os-views-client: "true"
    axon-showcase-redis-client: "true"
  networkPolicy:
    ingressManagementNSMatchLabels:
      name: monitoring
    ingressManagementNSPodMatchLabels:
      prometheus: kps
  serviceMonitor:
    namespace: monitoring
    labels:
      release: kps

apiGateway:
  ingress:
    enabled: true
    hostname: axon-showcase
  networkPolicy:
    ingressManagementNSMatchLabels:
      name: monitoring
    ingressManagementNSPodMatchLabels:
      prometheus: kps
  serviceMonitor:
    namespace: monitoring
    labels:
      release: kps

observability:
  metrics:
    prometheus:
      enabled: true
