fullnameOverride: axon-showcase

commandService:
  podLabels:
    axon-showcase-db-events-client: "true"
    axon-showcase-kafka-client: "true"
  autoscaling:
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 2
  networkPolicy:
    ingressManagementNSMatchLabels:
      name: monitoring
    ingressManagementNSPodMatchLabels:
      prometheus: kps
  serviceMonitor:
    namespace: monitoring
    labels:
      release: kps

projectionService:
  kafka:
    fetcher:
      consumerCount: 8
  podLabels:
    axon-showcase-kafka-client: "true"
    axon-showcase-os-views-client: "true"
    axon-showcase-redis-client: "true"
  networkPolicy:
    ingressManagementNSMatchLabels:
      name: monitoring
    ingressManagementNSPodMatchLabels:
      prometheus: kps
  serviceMonitor:
    namespace: monitoring
    labels:
      release: kps

queryService:
  podLabels:
    axon-showcase-os-views-client: "true"
    axon-showcase-redis-client: "true"
  networkPolicy:
    ingressManagementNSMatchLabels:
      name: monitoring
    ingressManagementNSPodMatchLabels:
      prometheus: kps
  serviceMonitor:
    namespace: monitoring
    labels:
      release: kps

apiGateway:
  ingress:
    enabled: true
    hostname: axon-showcase
  autoscaling:
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 2
  networkPolicy:
    ingressManagementNSMatchLabels:
      name: monitoring
    ingressManagementNSPodMatchLabels:
      prometheus: kps
  serviceMonitor:
    namespace: monitoring
    labels:
      release: kps

observability:
  prometheus:
    metrics:
      export:
        enabled: true
  otlp:
    tracing:
      export:
        enabled: true
        endpoint: http://tempo.monitoring.svc.cluster.local:4317
