{{- if .Values.commandService.autoscaling.hpa.enabled }}
{{- $labels := include "common.tplvalues.merge" (dict "values" (list .Values.commandService.labels .Values.commonLabels) "context" $) }}
apiVersion: {{ include "common.capabilities.hpa.apiVersion" (dict "context" $) }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "axon-showcase.command-service.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" $labels "context" $) | nindent 4 }}
    app.kubernetes.io/component: command-service
  {{- if or .Values.commandService.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.commandService.annotations .Values.commonAnnotations) "context" $) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" $ }}
    kind: Deployment
    name: {{ include "axon-showcase.command-service.fullname" $ }}
  minReplicas: {{ .Values.commandService.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.commandService.autoscaling.hpa.maxReplicas }}
  metrics:
  {{- if .Values.commandService.autoscaling.hpa.targetCPU }}
    - type: Resource
      resource:
        name: cpu
      {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" $) }}
        targetAverageUtilization: {{ .Values.commandService.autoscaling.hpa.targetCPU }}
      {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.commandService.autoscaling.hpa.targetCPU }}
      {{- end }}
  {{- end }}
  {{- if .Values.commandService.autoscaling.hpa.targetMemory }}
    - type: Resource
      resource:
        name: memory
      {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" $) }}
        targetAverageUtilization: {{ .Values.commandService.autoscaling.hpa.targetMemory }}
      {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.commandService.autoscaling.hpa.targetMemory }}
      {{- end }}
  {{- end }}
  {{- if .Values.commandService.autoscaling.hpa.metrics }}
  {{- include "common.tplvalues.render" (dict "value" .Values.commandService.autoscaling.hpa.metrics "context" $) | nindent 4 }}
  {{- end }}
{{- end }}
