{{- if .Values.commandService.networkPolicy.enabled }}
{{- $labels := include "common.tplvalues.merge" (dict "values" (list .Values.commandService.labels .Values.commonLabels) "context" $) }}
{{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.commandService.podLabels .Values.commonLabels) "context" $) }}
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" $ }}
kind: NetworkPolicy
metadata:
  name: {{ include "axon-showcase.command-service.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" $labels "context" $) | nindent 4 }}
    app.kubernetes.io/component: command-service
  {{- if or .Values.commandService.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.commandService.annotations .Values.commonAnnotations) "context" $) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" $) | nindent 6 }}
      app.kubernetes.io/component: command-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ .Values.commandService.containerPorts.server }}
    - ports:
        - port: {{ .Values.commandService.containerPorts.managementServer }}
      from:
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" $) | nindent 14 }}
        {{- if .Values.commandService.networkPolicy.addExternalClientAccess }}
        - podSelector:
            matchLabels:
              {{ include "common.names.fullname" $ }}-client: "true"
        {{- end }}
        {{- if .Values.commandService.networkPolicy.ingressPodMatchLabels }}
        - podSelector:
            matchLabels: {{- include "common.tplvalues.render" (dict "value" .Values.commandService.networkPolicy.ingressPodMatchLabels "context" $) | nindent 14 }}
        {{- end }}
        {{- if .Values.commandService.networkPolicy.ingressManagementNSMatchLabels }}
        - namespaceSelector:
            matchLabels:
              {{- range $key, $value := .Values.commandService.networkPolicy.ingressManagementNSMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- if .Values.commandService.networkPolicy.ingressManagementNSPodMatchLabels }}
          podSelector:
            matchLabels:
              {{- range $key, $value := .Values.commandService.networkPolicy.ingressManagementNSPodMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- end }}
        {{- end }}
    - ports:
        - port: {{ .Values.commandService.containerPorts.jgroups }}
      from:
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" $) | nindent 14 }}
              jgroups-cluster: axon-showcase
    {{- if .Values.commandService.networkPolicy.extraIngress }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commandService.networkPolicy.extraIngress "context" $) | nindent 4 }}
    {{- end }}
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "common.names.namespace" $ | quote }}
    {{- with (lookup "discovery.k8s.io/v1" "EndpointSlice" (include "common.names.namespace" $) "kubernetes") }}
    - to:
        {{- range .endpoints }}
        {{- range .addresses }}
        - ipBlock:
            cidr: {{ . }}/32
        {{- end }}
        {{- end }}
      ports:
        {{- range .ports }}
        - port: {{ .port }}
          protocol: {{ .protocol }}
        {{- end }}
    {{- end }}
    {{- if .Values.commandService.networkPolicy.extraEgress }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commandService.networkPolicy.extraEgress "context" $) | nindent 4 }}
    {{- end }}
{{- end }}
